### ISSUE TITLE
bug when generating metric names in parallel

### ISSUE THREAD

**Issue by vrischmann** [wazazaby/vimebu#36]
The following test fails:
```
func TestParallel(t *testing.T) {
	var wg sync.WaitGroup
	wg.Add(200)

	for i := 0; i < 200; i++ {
		i := i

		go func() {
			defer wg.Done()

			Metric(fmt.Sprintf("foobar%d", i)).
				Label("host", "foobar").
				Label("compressed", "false").
				GetOrCreateCounter().
				Add(300)
		}()
	}

	wg.Wait()
}
```

with this panic:
```
=== RUN   TestParallel
panic: BUG: invalid metric name "foobar117{host=\"foobar\",compressed=\"false\"": missing closing curly brace at the end of "foobar117"

goroutine 101 [running]:
github.com/VictoriaMetrics/metrics.(*Set).GetOrCreateCounter(0x105162a20, {0xc0000a80c0, 0x2a})
	/Users/vincent/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.33.0/set.go:167 +0x4d0
github.com/VictoriaMetrics/metrics.GetOrCreateCounter(...)
	/Users/vincent/go/pkg/mod/github.com/!victoria!metrics/metrics@v1.33.0/counter.go:85
github.com/wazazaby/vimebu.(*Builder).GetOrCreateCounter(0xc000315f90)
	/Users/vincent/dev/devtools/vimebu/victoria_metrics.go:11 +0x54
github.com/wazazaby/vimebu.TestParallel.func1()
	/Users/vincent/dev/devtools/vimebu/vimebu_test.go:404 +0x178
created by github.com/wazazaby/vimebu.TestParallel in goroutine 38
	/Users/vincent/dev/devtools/vimebu/vimebu_test.go:398 +0x70
FAIL	github.com/wazazaby/vimebu	0.139s
FAIL
```

It works fine with vimebu v1.2.1 but fails with v1.3.0

**Comment by wazazaby** [comment]
Thank you for spotting this. Looking into it.
